before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - id: cm
    main: ./cmd/chall-manager
    binary: chall-manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -cover
  - id: cmj
    main: ./cmd/chall-manager-janitor
    binary: chall-manager-janitor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -cover

dockers:
  - ids:
      - cm
    dockerfile: Dockerfile.chall-manager
    image_templates:
      - "ctferio/chall-manager:latest"
      - "ctferio/chall-manager:{{ .Tag }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=chall-manager"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
  - ids:
      - cmj
    dockerfile: Dockerfile.chall-manager-janitor
    image_templates:
      - "ctferio/chall-manager-janitor:latest"
      - "ctferio/chall-manager-janitor:{{ .Tag }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=chall-manager-janitor"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

source:
  enabled: true

checksum: {}

sboms:
  - artifacts: source
